name: DaddyNew
on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 3 ore: 0:00, 3:00, 6:00, 9:00, 12:00, 15:00, 18:00, 21:00 UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with custom token
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pygithub

      - name: Run Cacca
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python daddyautomatico.py

      - name: Commit and push changes
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          git add daddy.m3u8
          git commit -m "Aggiornamento automatico daddy.m3u8" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
