name: Download and Update FILM and SERIE List

on:
  schedule:
    - cron: '0 */12 * * *'  # Esegui ogni 12 ore
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download FILM M3U file
        run: curl -o film.m3u ${{ secrets.FILM }}

      - name: Download SERIE M3U file
        run: curl -o serie.m3u ${{ secrets.SERIE }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions-bot@github.com"

      - name: Commit and push if there are changes
        run: |
          git add film.m3u serie.m3u
          if git diff --staged --quiet; then
            echo "Nessuna modifica da committare."
          else
            git commit -m "Update film.m3u and serie.m3u list"
            git push
          fi
