name: Hattrick Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'  # প্রতি ৩ ঘণ্টা পর

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (using GITHUB_TOKEN)
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # এটি GitHub নিজে দেয়

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run Hattrick Scraper
        run: |
          python hattrickfunzionante.py

      - name: Commit and push updated M3U8 file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add hat.m3u8
          git commit -m "Updated M3U8 stream file" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
