name: Update itaevents2.m3u8

on:
  workflow_dispatch:  # Esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Ogni 15 minuti

jobs:
  update-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}  # Usa il token personalizzato

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run M3U8 updater
        run: |
          python modify_m3u8.py

      - name: Commit and push updated M3U8 file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add itaevents3.m3u8
          git commit -m "Aggiornato itaevents2.m3u8 con nuove header" || echo "Nessun cambiamento da committare"
          git push
        continue-on-error: true
