name: SportZone Scraper

on:
  workflow_dispatch:  # Permette l'esecuzione manuale
  schedule:
    - cron: '*/15 * * * *'  # Esegue ogni 15 minuti

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # Clona il repository
      - name: Clona il repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Recupera la storia completa per il rebase
          token: ${{ secrets.ACTIONS_TOKEN }}

      # Configura Python
      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Installa Google Chrome per Selenium
      - name: Installa Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Installa dipendenze Python
      - name: Installa dipendenze
        run: |
          python -m pip install --upgrade pip
          pip install requests cloudscraper beautifulsoup4 urllib3 selenium webdriver-manager

      # Esegui lo script Python
      - name: Esegui script SportZone
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
        run: |
          python SportZone\ Scraper/sportzone.py

      # Esegui commit delle modifiche locali, pull --rebase e push
      - name: Commit e push del file M3U8 aggiornato
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add sportzone.m3u8
          git commit -m "Aggiornamento temporaneo di sportzone.m3u8" || echo "Nessun cambiamento locale da committare"
          git pull --rebase origin main
          git add sportzone.m3u8
          git commit -m "Aggiornato file M3U8 con nuovi flussi" || echo "Nessun cambiamento da committare dopo il rebase"
          git push
