name: Unzip freeiptv-master.zip (No Push)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List files before unzip
        run: ls -la

      - name: Unzip freeiptv-master.zip
        run: unzip freeiptv-master.zip

      - name: List files after unzip
        run: ls -laR freeiptv-master
